name: Temporary RDP with Playit

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest

    steps:
    - name: Enable RDP and Set Password
      run: |
        # تفعيل RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

        # فتح الجدار الناري لـ RDP
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        # تعيين كلمة مرور
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "}5*E99!v?cfb87:[Ou[v" -Force)

        # التأكد من تشغيل خدمة RDP
        Set-Service -Name TermService -StartupType Automatic
        Start-Service -Name TermService

    - name: Download and Run Playit Agent
      env:
        PLAYIT_SECRET_KEY: ${{ secrets.PLAYIT_SECRET_KEY }}
      run: |
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "$env:USERPROFILE\playit.exe"
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_SECRET_KEY" -NoNewWindow

    - name: Keep Session Alive (6h)
      run: Start-Sleep -Seconds 21600
